### ISSUE TITLE
OBO Purl is wrong

### ISSUE THREAD

**Issue by StroemPhi** [rsc-ontologies/rxno#12]
Hi @colinbatchelor, 
the IRI provided in RXNO is http://purl.obolibrary.org/obo/rxno.obo.owl which resolves to http://ontologies.berkeleybop.org/
but it should be http://purl.obolibrary.org/obo/rxno.owl which resolves to https://raw.githubusercontent.com/rsc-ontologies/rxno/master/rxno.owl, right?

**Comment by StroemPhi** [comment]
can be closed, as it was resolved with #26

**Comment by batchelorc** [comment]
Thanks!
