### ISSUE TITLE
mop.obo & mop.owl are out of sync

### ISSUE THREAD

**Issue by hujo91** [rsc-ontologies/rxno#22]
When producing mop.obo from mop.owl using ROBOT convert, we can see that these two are out of sync for longer time. We happened to notice this while doing PR #21.
![Screenshot mop obo](https://user-images.githubusercontent.com/79629912/140067702-812a389c-795f-45df-8e21-18322d0d756f.png)

**Comment by StroemPhi** [comment]
@hujo91 I think you closed this with 1cc6d4da107a343a762f1c8af72b28476944dee9.

**Comment by hujo91** [comment]
@StroemPhi yes indeed. Thanks for this hint had neglected to close this still open issue.
