### ISSUE TITLE
Addition of 16 missing reactions to RXNO

### ISSUE THREAD

**Issue by hujo91** [rsc-ontologies/rxno#33]
Addition of 16 reactions:

1. Kabachnik-Fields reaction (RXNO:0000676)
Def.: A three-component condensation reaction in which primary or secondary amines react with a carbonyl compound (aldehyde or ketone) and a dialkyl phosphonate (also called dialkyl phosphite) to form an alpha-aminophosphonate.
Parent class: molecular skeleton joining reaction (RXNO:0000000) & molecular dehydration reaction (MOP:0000628)

2. Baekeland-Manasse-Lederer reaction (RXNO:0000677)
Def.: A polymerisation reaction in which phenol and formaldehyde react together in a chain reaction to form a phenol formaldehyde resin (also infrequently called phenoplast).
Parent class: polymerisation reaction (RXNO:0000246)

3. Aston-Greenburg rearrangement (RXNO:0000678)
Def.: The rearrangement of an alpha-haloketone into an ester with a tertiary alpha-carbon atom by intramolecular migration of an alkyl or aryl group.
Parent class: rearrangement step (RXNO:0000025)

4. Baddeley isomerization (RXNO:0000679)
Def.: The rearrangement/migration of alkyl groups in polyalkylbenzenes or polynuclear aromatic compounds in the presence of anhydrous aluminum chloride or the mixture of protonic acid and Lewis acid.
Parent class: rearrangement step (RXNO:0000025)

5. Fukuyama reduction (RXNO:0000680)
Def.: The reduction of a thioester to an aldehyde by a silyl hydride in the presence of catalytic amounts of palladium.
Parent class: functional group reduction (RXNO:0000037)

6. Dötz reaction (RXNO:0000681)
Def.: A three component cyclization of an aromatic or vinylic alkoxy pentacarbonyl chromium carbene complex, an alkyne and carbon monoxide to give a Cr(CO)3 coordinated phenol.
Parent class: ring formation reaction step (RXNO:0000005)
Synonym: Wulff-Dötz reaction

7. Kulinkovich reaction (RXNO:0000682)
Def.: The formation of a substituted cyclopropanol by reaction of a carboxylic ester with a Grignard reagent (carrying a hydrogen atom in the beta-position) in the presence of a titanium(IV) alkoxide as catalyst. A modified cyclopropanol product can be generated by addition of a terminal alkene as a further reactant.
Parent class: ring formation reaction step (RXNO:0000005)

8. Kulinkovich-de Meijere reaction (RXNO:0000683)
Def.: The formation of a substituted cyclopropylamine by reaction of an amide with a Grignard reagent (carrying a hydrogen atom in the beta-position) in the presence of a titanium(IV) alkoxide as catalyst.
Parent class: ring formation reaction step (RXNO:0000005)

9. Kulinkovich-Szymoniak reaction (RXNO:0000684)
Def.: The formation of a substituted primary cyclopropylamine by reaction of a nitrile with a Grignard reagent (carrying a hydrogen atom in the beta-position) in the presence of a titanium(IV) alkoxide as catalyst.
Parent class: ring formation reaction step (RXNO:0000005)

> 10. cyclotrimerization (RXNO:0000685)
> Def.: The formation of a trimer by cycloaddition of three unsaturated compounds (e.g. alkynes, alkenes, nitriles or mixtures of these). Usually, the reaction requires a metal catalyst.
> Parent class: ring formation reaction step (RXNO:0000005) & cycloaddition (MOP:0000562)
> => not added to RXNO because it fits better in the scope of MOP and will be added there, see #34

11. Jacobsen epoxidation (RXNO:0000686)
Def.: Chiral (salen)manganese(III)-catalyzed asymmetric epoxidation of alkenes. In addition to the catalyst, stoichiometric amounts of an oxidant (e.g. sodium hypochlorite) are required.
Parent class: ring formation reaction step (RXNO:0000005) & epoxidation (MOP:0000671)
Synonym: Jacobsen-Katsuki epoxidation

12. Shi epoxidation (RXNO:0000687)
Def.: Organocatalytic enantioselective epoxidation of trans- and tri-substituted olefins using a fructose derived chiral ketone catalyst and potassium peroxomonosulfate or H2O2 as an oxidant.
Parent class: ring formation reaction step (RXNO:0000005) & epoxidation (MOP:0000671)

13. Asinger reaction (RXNO:0000688)
Def.: A multicomponent reaction (A-4CR) in which 3-thiazolines (2,5-dihydro-1,3-thiazoles) or mixtures of several 3-thiazolines are synthesized from elemental sulfur, an alpha-substitutable ketone or aldehyde, another carbonyl component and ammonia.
Parent class: ring formation reaction step (RXNO:0000005) & thiacycle synthesis (RXNO:0000348)
Synonym: Asinger thiazoline synthesis & Asinger-4 component reaction (A-4CR)

14. haloform reaction (RXNO:0000689)
Def.: Cleavage of methyl ketones (i.e. oxidative demethylation) with halogens (or hypohalites) in the presence of a base to give a carboxylic acid and haloform (trihalomethane).
Parent class: end-of-chain chain shortening (RXNO:0000105) & halogenation (MOP:0000550)
Synonym: Einhorn reaction & Lieben reaction

15. Atherton-Todd reaction (RXNO:0000690)
Def.: The conversion of dialkyl phosphites (dialkyl phosphonates) to dialkyl chlorophosphates using tetrachloromethane and a base (usually a primary, secondary or tertiary amine).
Parent class: functional group oxidation (RXNO:0000012) & halogenation (MOP:0000550)
Synonym: AT reaction

16. Baeyer diarylmethane synthesis (RXNO:0000691)
Def.: Synthesis of diarylmethane derivatives using an aldehyde and an aromatic compound at low temperature in an acidic medium.
Parent class: molecular skeleton joining reaction (RXNO:0000000) & molecular dehydration reaction (MOP:0000628)

17. silyl deprotection (RXNO:0000692)
Def.: A hydroxyl group deprotection in which an silyl ether group is transformed into a hydroxy group.
Parent class: hydroxy group deprotection (RXNO:0000430)

**Comment by hujo91** [comment]
futhermore improvements & some more minor updates/additions:

- Addition of new "has specified reactant", "has specified product" & "has_catalyst" relationships to existing reactions "Fukuyama coupling" (RXNO:0000605) & "Liebeskind-Srogl coupling" (RXNO:0000604).
- import of some new substances from ChEBI under "molecular entity" class
- import of class "chemical substance" from ChEBI

**Comment by batchelorc** [comment]
Two things to add:

RXNO:0000676 - this is also a molecular dehydration reaction (MOP:0000628)
RXNO:0000681 - probably useful to have "Wulff–Dötz reaction" as a synonym

**Comment by hujo91** [comment]
> Two things to add:
> 
> RXNO:0000676 - this is also a molecular dehydration reaction (MOP:0000628) RXNO:0000681 - probably useful to have "Wulff–Dötz reaction" as a synonym

@batchelorc thanks for the hints, I have taken them into account.
One question regarding 10. cyclotrimerization (RXNO:0000685): Does the definition fit and does this reaction really belong in RXNO or would it not fit better in MOP due to its rather general character?

**Comment by batchelorc** [comment]
cyclotrimerization better for MOP, I think
