### ISSUE TITLE
Addition of trimerization, cyclotrimerization & protein trimerization to MOP

### ISSUE THREAD

**Issue by hujo91** [rsc-ontologies/rxno#34]
Addition of 3 missing reactions:

1. trimerization (MOP:0000715)
Def.: The formation of a trimer from three molecular subunits.
Parent class: molecular process (MOP:0000543)

2. cyclotrimerization (MOP:0000716)
Def.: The formation of a trimer by cycloaddition of three unsaturated compounds (e.g. alkynes, alkenes, nitriles or mixtures thereof). A metal catalyst is usually required for this type of reaction.
Parent class: cycloaddition (MOP:0000562) & trimerization (MOP:0000715)
Source: https://doi.org/10.1002/anie.200700802

3. protein trimerization (GO:0070206) - **Import from Gene Ontology**
Def.: The formation of a protein trimer, a macromolecular structure consisting of three noncovalently associated identical or nonidentical subunits.
Parent class: trimerization (MOP:0000715)
Source: http://purl.obolibrary.org/obo/GO_0070206

note:
- also added "dc:date" to the ontology header

**Comment by batchelorc** [comment]
I think it's best to go for the lowest unused MOP ID, which is MOP:0000825.

**Comment by batchelorc** [comment]
But here's a thing - is it a cyclisation according to the Gold Book definition? I'm not sure it is.

**Comment by hujo91** [comment]
[Definition of "cyclization" in the Goldbook](https://goldbook.iupac.org/terms/view/C01494): "Formation of a ring compound from a chain by formation of a new bond."
According to this definition, I guess it is indeed the case that cyclotrimerization is not cyclization (MOP:0000561), because it does not happen from a chain.
Thanks for the hint! 
Anyway, I think that actually a definition of cyclotrimerization should also be included in the Goldbook in the future. Maybe I will suggest that. @batchelorc your opinion on this?

**Comment by batchelorc** [comment]
There is no harm in suggesting new terms for the Gold Book, but it might well take a while.

The other thing I am wondering is whether there are any trimerisations that aren't cyclic?

**Comment by hujo91** [comment]
So, as I understand it, the essential feature of trimerization is the formation of a trimer from three molecular subunits. This can be done as cyclotrimerization by cycloaddition and thus formation of a cyclic trimer. However, this need not be necessarily the case. I am thinking, for example, of the [metal-catalyzed trimerization of ethene to 1-hexene](https://doi.org/10.1016/j.molcata.2003.10.056), as a trimerization without ring formation. That would be more in the sense of an oligomerization.
All in all, I would say that cyclotrimerization is a (common) special case of trimerization.

**Comment by StroemPhi** [comment]
Do I understand you two right, that this means we also need to add to MOP a parent class called "trimerization" under which to subsume "cyclotrimerization" as well as probably GO's [protein trimerization](http://purl.obolibrary.org/obo/GO_0070206) and the one from the above example?

If so, I assume the parent class of "trimerization" to be "molecular process (MOP:0000543), right?

**Comment by hujo91** [comment]
@StroemPhi, yes I think that sums it up quite well.
Parent class "trimerization" ([metal-catalyzed trimerization of ethene to 1-hexene](https://doi.org/10.1016/j.molcata.2003.10.056)) under "molecular process (MOP:0000543), with the subclass "cyclotrimerization" and maybe also "[protein trimerization](purl.obolibrary.org/obo/GO_0070206)" from GO?
@batchelorc your opinion on that?

**Comment by StroemPhi** [comment]
I think it was a bad idea to include GO's "[protein trimerization](https://github.com/rsc-ontologies/rxno/issues/purl.obolibrary.org/obo/GO_0070206)" and propose to get it out of MOP again as it is not within the scope of MOP. If it was me introducing this error, than I'm really sorry.

**Comment by StroemPhi** [comment]
see also https://github.com/rsc-ontologies/rxno/issues/45
