### ISSUE TITLE
Missing reaction SMARTS

### ISSUE THREAD

**Issue by jasondbiggs** [rsc-ontologies/rxno#9]
I notice that when I go to [this page](https://www.rsc.org/publishing/journals/prospect/ontology.asp?id=RXNO:0000006) for the Diels-Alder reaction it has "[C:1]=[C:2][C:3]=[C:4].[C:5]=[C:6]>>[C:1]1[C:2]=[C:3][C:4][C:5][C:6]1" listed as a synonym.  

I see that these SMARTS strings (or maybe SMIRKS, I'm very unclear on the difference) were removed from this repo four years ago and wanted to ask why.  Were these SMARTS strings not very good representations of the reactions in question?

**Comment by batchelorc** [comment]
Hello,

Thank you for your interest in RXNO. It turns out that the task of writing these is very much more complicated, with more edge cases, than I had realised and it seemed safest on reflection to go without.

Best wishes,
Colin.
